theme: jekyll-theme-midnight

title: "Salmon run NW scenarios"
description: "Here is a list of scenario codes I have played or had friends share with me."
logo: img/eddie.png

twitter:
  username: eddie_splatoon
